Allow spaces
ros/resource_retriever pull request #100
Opened 2024-05-14 13:03 UTC by ahcorde

Related with this PR https://github.com/ros/resource_retriever/pull/85 in the ROS 1 version

2024-06-11 08:07 UTC, ahcorde commented
friendly ping @clalancette

2024-06-11 12:15 UTC, clalancette requested changes

2024-06-11 12:15 UTC, clalancette commented on resource_retriever/src/retriever.cpp
> +  mod_url = std::regex_replace(mod_url, std::regex(" "), "%20");
Use `std::regex` here seems like overkill, and will likely be much slower than just iterating over the list and replacing.  So I think we should just do this by hand, something like:

```
    std::string new_mod_url;
    new_mod_url.reserve(mod_url.length());

    std::string::size_type last_pos = 0;
    std::string::size_type find_pos;

    while(std::string::npos != (find_pos = mod_url.find(" ", last_pos)))
    {
        new_mod_url.append(mod_url, last_pos, find_pos - last_pos);
        new_mod_url += "%20";
        last_pos = find_pos + " ".length();
    }

    // Take care for the rest after last occurrence
    new_mod_url.append(mod_url, last_pos, mod_url.length() - last_pos);

    mod_url = new_mod_url;
```

(adapted from https://stackoverflow.com/questions/2896600/how-to-replace-all-occurrences-of-a-character-in-string)

2024-06-12 12:27 UTC, clalancette requested changes
Sorry, one more minor revamp, then I think this will be good.

2024-06-12 12:27 UTC, clalancette commented on resource_retriever/src/retriever.cpp
> +  mod_url = new_mod_url;
I know I didn't say this in my initial review, but I'm going to suggest we move this into a function called something like `escape_spaces`, with a signature like:

```
std::string escape_spaces(const std::string & url)
```

That way it is clear in the flow here that we want to escape them.

2024-06-14 12:12 UTC, clalancette requested changes

2024-06-14 12:12 UTC, clalancette commented on resource_retriever/src/retriever.cpp
> +std::string Retriever::escape_spaces(const std::string & url)
I don't think we need to make this part of the class; it never accesses anything in it, so it can just be a free function:

```suggestion
static std::string escape_spaces(const std::string & url)
```

2024-06-14 12:12 UTC, clalancette commented on resource_retriever/include/resource_retriever/retriever.hpp
> +  std::string escape_spaces(const std::string & url);
```suggestion
```

2024-06-14 12:12 UTC, clalancette commented on resource_retriever/src/retriever.cpp
> +  while(std::string::npos != (find_pos = url.find(" ", last_pos))) {
```suggestion
  while (std::string::npos != (find_pos = url.find(" ", last_pos))) {
```

2024-06-14 12:33 UTC, clalancette approved these changes
Looks good to me with green CI!  Thanks for the iteration.

2024-06-14 12:56 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21267)](http://ci.ros2.org/job/ci_linux/21267/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15586)](http://ci.ros2.org/job/ci_linux-aarch64/15586/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=762)](http://ci.ros2.org/job/ci_linux-rhel/762/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21993)](http://ci.ros2.org/job/ci_windows/21993/)

2024-06-17 12:57 UTC, merged

2024-06-17 12:57 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy