Add a plugin mechanism to resource_retriever
ros/resource_retriever pull request #103
Opened 2024-08-16 19:54 UTC by mjcarroll

The idea behind this is to make `resource_retriever` pluggable.  That is that downstream users of the library can choose the mechanisms that they want to back the calls to "get".

This will allow for things like retrieving over ROS services or parameters.

2024-08-17 00:00 UTC, wjwwood approved these changes
This makes sense to me, it's the best way to avoid resource retriever from being dependent on large things like ROS, while also keeping it somewhat easy to integrate into other non-ROS projects for relatively simple things like `file:///` and `package:///` urls.

2024-08-19 08:45 UTC, ahcorde requested changes, later dismissed

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/include/resource_retriever/plugins/curl_retriever.hpp
> +#include <vector>
remove

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/include/resource_retriever/plugins/curl_retriever.hpp
> +#include <cstdint>
remove

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/include/resource_retriever/plugins/filesystem_retriever.hpp
> +#include <vector>
remove

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/include/resource_retriever/plugins/filesystem_retriever.hpp
> +#include <stdexcept>
remove

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/src/plugins/curl_retriever.cpp
> +std::string CurlRetriever::name() {
```suggestion
}

std::string CurlRetriever::name() {
```

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/include/resource_retriever/plugins/curl_retriever.hpp
> +  CURL * curl_handle_ {nullptr};
smartptr?

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/src/plugins/curl_retriever.cpp
> +      fprintf(stderr, "Error initializing libcurl! retcode = %d", ret);
std::cerr ?
```suggestion
      fprintf(stderr, "Error initializing libcurl! retcode = %d", ret);
```

2024-08-19 08:45 UTC, ahcorde commented on resource_retriever/src/plugins/curl_retriever.cpp
> +std::string CurlRetriever::name() {
```suggestion
}

std::string CurlRetriever::name() {
```

2024-08-21 16:16 UTC, Voldivh commented on resource_retriever/src/plugins/curl_retriever.cpp
> +      fprintf(stderr, "Error initializing libcurl! retcode = %d", ret);
We would have to include the `iostream` library, Do we prefer that over using `stderr`?

2024-08-21 19:05 UTC, Yadunund commented on resource_retriever/include/resource_retriever/memory_resource.hpp
> +    data(std::move(data))
Apple Clang seems to have issues here; does it make sense to disambiguate `data` this way?
```suggestion
struct RESOURCE_RETRIEVER_PUBLIC MemoryResource
{
  explicit MemoryResource(std::vector<uint8_t> data_):
    data(std::move(data_))
```

2024-11-19 17:33 UTC, wjwwood commented on resource_retriever/include/resource_retriever/memory_resource.hpp
> +    data(std::move(data))
I added `_in` suffixes instead to avoid the shadowing: [10dfacf](https://github.com/ros/resource_retriever/pull/103/commits/10dfacf9f50a86b8cd8aba8e67ac7e6f2a73b623)

2024-12-03 16:11 UTC, mjcarroll commented on resource_retriever/include/resource_retriever/plugins/curl_retriever.hpp
> +  CURL * curl_handle_ {nullptr};
This specifically needs `curl_easy_init()` and `curl_easy_cleanup()` so smart pointers probably don't make sense here.

2024-12-03 16:14 UTC, mjcarroll commented on resource_retriever/src/plugins/curl_retriever.cpp
> +      fprintf(stderr, "Error initializing libcurl! retcode = %d", ret);
I went ahead and updated.

2024-12-03 18:13 UTC, clalancette requested changes

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/src/plugins/curl_retriever.cpp
> +      std::cerr << "Error initializing libcurl! retcode = " << ret;
Should we throw an exception here?  That way we wouldn't need the `initialized_` variable at all.

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/src/plugins/curl_retriever.cpp
> +#include <vector>
```suggestion
#include <cstring>
#include <iostream>
#include <memory>
#include <string>
#include <utility>
#include <vector>
```

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/src/plugins/curl_retriever.cpp
> +  return  url.find("package://") == 0 ||
```suggestion
  return url.find("package://") == 0 ||
```

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/src/plugins/filesystem_retriever.cpp
> +#include <vector>
```suggestion
#include <fstream>
#include <memory>
#include <string>
#include <vector>
```

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/src/plugins/retriever_plugin.cpp
> +#include <cstring>
```suggestion
#include <cstring>
#include <string>
```

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/src/retriever.cpp
>  #include <vector>
```suggestion
#include <memory>
#include <string>
#include <utility>
```

2024-12-03 18:13 UTC, clalancette commented on resource_retriever/test/test.cpp
```suggestion
#include <memory>
#include <vector>
```

(and alphabetize it with the above)

2024-12-03 21:14 UTC, wjwwood commented on resource_retriever/src/plugins/curl_retriever.cpp
> +      std::cerr << "Error initializing libcurl! retcode = " << ret;
I think the issue is that this is used a static global, so it's not possible to catch the exception.

However, I agree this isn't great.

I considered at least saying it should go through some injectable logging (so we could pipe it to ROS logging for example), but that's hard too since this is a global.

I think maybe it shouldn't print anything and instead it should just set the flag and the first place to try and use it should throw an exception since it's not initialized.

But I'll have to think about it more.

2024-12-14 00:24 UTC, wjwwood commented on resource_retriever/src/plugins/curl_retriever.cpp
> +      std::cerr << "Error initializing libcurl! retcode = " << ret;
I reworked this to throw an exception the first time we attempt to use curl rather than print an error here.

2024-12-14 00:25 UTC, wjwwood commented
I fixed up the DCO and addressed review comments in [8a30432](https://github.com/ros/resource_retriever/pull/103/commits/8a30432ca9a5e385a941c97373b783d6a6935ff6), @clalancette could you have another quick look?

2024-12-18 22:13 UTC, clalancette submitted a review, later dismissed

2024-12-18 22:13 UTC, clalancette commented on resource_retriever/include/resource_retriever/retriever.hpp
>  #include <stdexcept>
```suggestion
```

2024-12-18 22:13 UTC, clalancette commented on resource_retriever/include/resource_retriever/retriever.hpp
> +  MemoryResourcePtr get(const std::string & url);
This is an important change to the API, going from returning a structure to returning a shared_ptr.  Given that we usually tick-tock this stuff, can we add back the old API and mark it as deprecated?

2025-02-14 21:56 UTC, wjwwood commented on resource_retriever/include/resource_retriever/retriever.hpp
> +  MemoryResourcePtr get(const std::string & url);
Done in [594fe30](https://github.com/ros/resource_retriever/pull/103/commits/594fe3070efb23b879d4f42f544bec7fb5c93792)

2025-02-18 19:13 UTC, Yadunund approved these changes
LGTM with a comment on copyright headers.

2025-02-18 19:13 UTC, Yadunund commented on resource_retriever/include/resource_retriever/exception.hpp
> +// Copyright 2009, Willow Garage, Inc. All rights reserved.
Do we want to update the copyright headers to 2025 and attribute OSRF?

2025-02-18 21:33 UTC, wjwwood commented on resource_retriever/include/resource_retriever/exception.hpp
> +// Copyright 2009, Willow Garage, Inc. All rights reserved.
We can add an OSRF 2025 but we can't change it.

2025-02-18 21:55 UTC, ahcorde requested changes

2025-02-18 21:55 UTC, ahcorde commented on resource_retriever/include/resource_retriever/memory_resource.hpp
> +    std::vector<uint8_t> data_in)
include `<cstdint>`

2025-02-18 21:55 UTC, ahcorde commented on resource_retriever/include/resource_retriever/memory_resource.hpp
> +using MemoryResourceSharedPtr = std::shared_ptr<MemoryResource>;
include `<memory>`

2025-02-18 21:55 UTC, ahcorde commented on resource_retriever/include/resource_retriever/retriever.hpp
> +   * \param url The url to retrieve.  package://package/file will be turned into the correct file:// invocation
```suggestion
   * \param url The url to retrieve. package://package/file will be turned into the correct file:// invocation
```

2025-02-18 21:55 UTC, ahcorde commented on resource_retriever/src/plugins/curl_retriever.cpp
> +  std::vector<uint8_t> v;
include `<cstdint>`

2025-02-18 21:55 UTC, ahcorde commented on resource_retriever/src/plugins/filesystem_retriever.cpp
> +    std::streampos fileSize = file.tellg();
include `<ios>`

2025-02-18 23:02 UTC, wjwwood commented on resource_retriever/include/resource_retriever/memory_resource.hpp
> +using MemoryResourceSharedPtr = std::shared_ptr<MemoryResource>;
I think we already are, did you mean to put this comment somewhere else?

2025-02-19 08:57 UTC, ahcorde approved these changes

2025-02-19 08:58 UTC, ahcorde commented
Pulls: ros/resource_retriever#103
Gist: https://gist.githubusercontent.com/ahcorde/9e7444d1b56419e258ff10755d70746b/raw/86df9c511efc6fef5cd9d84105d21785973d9df4/ros2.repos
BUILD args:  --packages-above-and-dependencies resource_retriever
TEST args:  --packages-above resource_retriever
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15218
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22561)](http://ci.ros2.org/job/ci_linux/22561/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16806)](http://ci.ros2.org/job/ci_linux-aarch64/16806/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2077)](http://ci.ros2.org/job/ci_linux-rhel/2077/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23354)](http://ci.ros2.org/job/ci_windows/23354/)

2025-02-19 09:38 UTC, ahcorde commented
Pulls: ros/resource_retriever#103, ros2/rviz#1262
Gist: https://gist.githubusercontent.com/ahcorde/13502377fe7128ba0a2d910a7c9dfd91/raw/2b32e8eeb4f5c28e7b0afbbdb6ea9f15771e6234/ros2.repos
BUILD args:  --packages-above-and-dependencies resource_retriever
TEST args:  --packages-above resource_retriever
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15221
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22564)](http://ci.ros2.org/job/ci_linux/22564/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16809)](http://ci.ros2.org/job/ci_linux-aarch64/16809/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2080)](http://ci.ros2.org/job/ci_linux-rhel/2080/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23357)](http://ci.ros2.org/job/ci_windows/23357/)

2025-02-19 15:34 UTC, mjcarroll commented on resource_retriever/include/resource_retriever/memory_resource.hpp
> +using MemoryResourceSharedPtr = std::shared_ptr<MemoryResource>;
Confirmed that memory is already included here.

2025-02-19 20:50 UTC, ahcorde requested changes

2025-02-19 20:50 UTC, ahcorde commented on resource_retriever/src/plugins/filesystem_retriever.cpp
> +    file.read(reinterpret_cast<char *>(data.data()), fileSize);
we can replace these line with (include `<iterator>`):

```suggestion
    std::vector<uint8_t> data(std::istreambuf_iterator<char>(file), {});
```

2025-03-04 23:37 UTC, mjcarroll commented
Pulls: ros/resource_retriever#103
Gist: https://gist.githubusercontent.com/mjcarroll/cc5568432e45f4a942cb2b519c381f26/raw/86df9c511efc6fef5cd9d84105d21785973d9df4/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15285
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22633)](http://ci.ros2.org/job/ci_linux/22633/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16876)](http://ci.ros2.org/job/ci_linux-aarch64/16876/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2150)](http://ci.ros2.org/job/ci_linux-rhel/2150/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23444)](http://ci.ros2.org/job/ci_windows/23444/)

2025-03-05 01:18 UTC, wjwwood commented
I fixed the API breaks in [67b9130](https://github.com/ros/resource_retriever/pull/103/commits/67b9130054dbaead176923f381d950143805f60f) and [a7607e6](https://github.com/ros/resource_retriever/pull/103/commits/a7607e61815189ad9987f73c1db79877f7480e46). Should be good to re-run CI.

2025-03-05 13:57 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22636)](http://ci.ros2.org/job/ci_linux/22636/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16879)](http://ci.ros2.org/job/ci_linux-aarch64/16879/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2153)](http://ci.ros2.org/job/ci_linux-rhel/2153/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23447)](http://ci.ros2.org/job/ci_windows/23447/)

2025-03-07 19:28 UTC, wjwwood commented
Looks like ci was interrupted?

2025-03-07 21:32 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22662)](http://ci.ros2.org/job/ci_linux/22662/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16904)](http://ci.ros2.org/job/ci_linux-aarch64/16904/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2178)](http://ci.ros2.org/job/ci_linux-rhel/2178/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23489)](http://ci.ros2.org/job/ci_windows/23489/)

2025-03-11 19:46 UTC, wjwwood commented
> * Linux [![Build Status](https://camo.githubusercontent.com/63c5a4739bf26419a71627073e96839b882197b9a25640c81a275955ddac4369/687474703a2f2f63692e726f73322e6f72672f6275696c645374617475732f69636f6e3f6a6f623d63695f6c696e7578266275696c643d3232363632)](http://ci.ros2.org/job/ci_linux/22662/)
> * Linux-aarch64 [![Build Status](https://camo.githubusercontent.com/7bada8bdf5056c43cd4354946893f5e1f8184a2fe730d9657cd97cb15b0fd196/687474703a2f2f63692e726f73322e6f72672f6275696c645374617475732f69636f6e3f6a6f623d63695f6c696e75782d61617263683634266275696c643d3136393034)](http://ci.ros2.org/job/ci_linux-aarch64/16904/)
> * Linux-rhel [![Build Status](https://camo.githubusercontent.com/7eb8d845da217c02784ec74b58b6f8eca61680a44b766aa76c8ef16efcac1860/687474703a2f2f63692e726f73322e6f72672f6275696c645374617475732f69636f6e3f6a6f623d63695f6c696e75782d7268656c266275696c643d32313738)](http://ci.ros2.org/job/ci_linux-rhel/2178/)
> * Windows [![Build Status](https://camo.githubusercontent.com/749cfa83682836f63a7ae0a559f59dec68ce2011643c1c530ed4d1e3f7e7ac07/687474703a2f2f63692e726f73322e6f72672f6275696c645374617475732f69636f6e3f6a6f623d63695f77696e646f7773266275696c643d3233343839)](http://ci.ros2.org/job/ci_windows/23489/)

I think this CI was with the rviz changes too, which I still need to update. I'm going to re-run what @mjcarroll did before which was testing that these changes only introduced deprecation warnings (without the rviz changes):

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22699)](http://ci.ros2.org/job/ci_linux/22699/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16938)](http://ci.ros2.org/job/ci_linux-aarch64/16938/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2213)](http://ci.ros2.org/job/ci_linux-rhel/2213/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23547)](http://ci.ros2.org/job/ci_windows/23547/)

2025-03-11 22:45 UTC, wjwwood commented
I fixed up the rviz changes now too in ros2/rviz2@9c3ea584. So I'll rerun your CI @ahcorde:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22703)](http://ci.ros2.org/job/ci_linux/22703/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16941)](http://ci.ros2.org/job/ci_linux-aarch64/16941/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2216)](http://ci.ros2.org/job/ci_linux-rhel/2216/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23553)](http://ci.ros2.org/job/ci_windows/23553/)

2025-03-12 16:50 UTC, wjwwood commented
Weirdly gcc 11.5 on RHEL doesn't like two attributes on a struct, Windows and whatever we're using on Ubuntu don't mind, see this godbolt with 11.4 (closest I could find on there):

https://godbolt.org/z/r8obexM18

I guess I'll just not deprecate it on RHEL? I'm not sure what to do here. @cottsay FYI in case this comes up anywhere else.

2025-03-12 17:37 UTC, wjwwood commented
I managed this workaround (I think): [5e78208](https://github.com/ros/resource_retriever/pull/103/commits/5e78208093e09cf44247cfc2aca571effc9fa4eb)

New CI (just up to resource_retriever and no rviz changes because I need to investigate rviz test failures first):

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22715)](http://ci.ros2.org/job/ci_linux/22715/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16952)](http://ci.ros2.org/job/ci_linux-aarch64/16952/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2231)](http://ci.ros2.org/job/ci_linux-rhel/2231/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23580)](http://ci.ros2.org/job/ci_windows/23580/)

2025-03-12 18:31 UTC, wjwwood commented
[7b55419](https://github.com/ros/resource_retriever/pull/103/commits/7b55419ce9e0156de0e1c002c4a0390baa98ce3c) should fix the issues in rviz.

CI without rviz changes:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22716)](http://ci.ros2.org/job/ci_linux/22716/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16953)](http://ci.ros2.org/job/ci_linux-aarch64/16953/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2233)](http://ci.ros2.org/job/ci_linux-rhel/2233/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23581)](http://ci.ros2.org/job/ci_windows/23581/)

CI with rviz changes (https://github.com/ros2/rviz/pull/1262):

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22717)](http://ci.ros2.org/job/ci_linux/22717/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16954)](http://ci.ros2.org/job/ci_linux-aarch64/16954/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2233)](http://ci.ros2.org/job/ci_linux-rhel/2233/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23581)](http://ci.ros2.org/job/ci_windows/23581/)

2025-03-13 00:29 UTC, wjwwood commented
I restored the old exception throwing behavior in [6f5eb98](https://github.com/ros/resource_retriever/pull/103/commits/6f5eb98e684d275105a2d8b1488b3b360850c929), which some of the rviz tests relied on, but we should really preserve if we can.

2025-03-13 00:30 UTC, wjwwood commented
Another round of CI without changes to rviz:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22721)](http://ci.ros2.org/job/ci_linux/22721/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16958)](http://ci.ros2.org/job/ci_linux-aarch64/16958/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2238)](http://ci.ros2.org/job/ci_linux-rhel/2238/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23586)](http://ci.ros2.org/job/ci_windows/23586/)

2025-03-13 01:17 UTC, wjwwood commented
Yet another round of CI without rviz changes, this time after running the tests locally 🤦 :

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22722)](http://ci.ros2.org/job/ci_linux/22722/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16959)](http://ci.ros2.org/job/ci_linux-aarch64/16959/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2239)](http://ci.ros2.org/job/ci_linux-rhel/2239/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23587)](http://ci.ros2.org/job/ci_windows/23587/)

2025-03-13 16:05 UTC, wjwwood commented
I forgot to push... man I'm on the struggle 🚌 , CI without rviz changes again:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22725)](http://ci.ros2.org/job/ci_linux/22725/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16967)](http://ci.ros2.org/job/ci_linux-aarch64/16967/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2242)](http://ci.ros2.org/job/ci_linux-rhel/2242/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23598)](http://ci.ros2.org/job/ci_windows/23598/)

2025-04-03 16:34 UTC, merged